version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Required environment variables - update these
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
      - XAI_API_KEY=${XAI_API_KEY}
      # Optional environment variables
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN:-}
      - N8N_API_KEY=${N8N_API_KEY:-}
      - N8N_BASE_URL=${N8N_BASE_URL:-}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-Automatic Chat Template}
      - NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION:-AI Chat Application}
    env_file:
      - .env.local
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Local development with Supabase
  supabase:
    profiles:
      - supabase
    image: supabase/supabase:latest
    ports:
      - "54321:8000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - supabase_data:/var/lib/supabase
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  supabase_data:
